services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-server
    depends_on:
      - postgresql-db
      - redis-service
      - rabbitmq
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis-service:6379/0
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend-network
    ports:
      - "8000:8000"

  postgresql-db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"


  redis-service:
    image: redis:alpine
    container_name: redis
    networks:
      - backend-network
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge